spring.application.name=demo

# Keycloak
keycloak.base-url=http://localhost:9090
keycloak.realm=patient-portal

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=admin
spring.datasource.password=password

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Resource Server Configuration
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/patient-portal
spring.security.oauth2.resourceserver.jwt.issuer-uri=${keycloak.base-url}/realms/${keycloak.realm}

# Client Configuration
# spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/patient-portal
spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.base-url}/realms/${keycloak.realm}
spring.security.oauth2.client.registration.keycloak.client-id=frontend
spring.security.oauth2.client.registration.keycloak.client-secret=1DstED1kOcQnhvoISr5I5x9d1CLEZfj4
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

# frontend base url
app.base-url=http://localhost:${server.port:8080}

# Error
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
spring.thymeleaf.cache=false

# Pageable limit
spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.max-page-size=20

# Rabitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=insurance
spring.rabbitmq.password=password

# Keycloak Admin Client Configuration
keycloak.client-id=backend-service
keycloak.client-secret=33iVIEwF4Nib1M3HqKNpGqsRhFrcOs3s

# Keycloak Account and Password URLs for user account management.
keycloak.account-url=${keycloak.base-url}/realms/${keycloak.realm}/account
keycloak.password-url=${keycloak.account-url}/account-security/signing-in
# keycloak.account-url=http://localhost:9090/realms/patient-portal/account
# keycloak.password-url=http://localhost:9090/realms/patient-portal/account/account-security/signing-in

# NOTE: TEMPORARILY SHUTTING DOWN RABBITMQ FOR TESTING PURPOSES
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration